theme: jekyll-theme-midnight
title: Origins and Evolution of Language
description: Academic year 2022-2023
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
